import { Archive, Edit3, Plus, Save, X } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { CloudinaryImageUploader } from '../../components/admin/CloudinaryImageUploader'
import { AdminPageHeader, Panel, inputClass, primaryButton, secondaryButton } from '../../components/admin/AdminUi'
import { adminApi } from '../../services/api'
import type { Category } from '../../types'

const empty = { name: '', slug: '', description: '', imageUrl: '', isActive: true, sortOrder: 0 }

export function AdminCategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([])
  const [form, setForm] = useState(empty)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const load = () => adminApi.get<{ data: { categories: Category[] } }>('/categories/admin').then((result) => setCategories(result.data.categories)).catch((err) => setError(err.message))
  useEffect(() => { void load() }, [])
  const edit = (category: Category) => { setEditingId(category.id); setForm({ name: category.name, slug: category.slug, description: category.description, imageUrl: category.imageUrl ?? category.image ?? '', isActive: category.isActive ?? true, sortOrder: category.sortOrder ?? 0 }) }
  const reset = () => { setEditingId(null); setForm(empty) }
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); try { await adminApi.mutate(`/categories/admin${editingId ? `/${editingId}` : ''}`, { method: editingId ? 'PUT' : 'POST', body: JSON.stringify(form) }); reset(); load() } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo guardar.') } }
  const archive = async (category: Category) => { if (!window.confirm(`¿Archivar la categoría “${category.name}”?`)) return; try { await adminApi.mutate(`/categories/admin/${category.id}`, { method: 'DELETE' }); load() } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo archivar.') } }
  return <><AdminPageHeader eyebrow="CATÁLOGO" title="Categorías" description="Organiza el catálogo y controla qué grupos aparecen en la tienda." />
    <div className="grid items-start gap-6 xl:grid-cols-[1fr_390px]"><Panel><div className="grid gap-3">{categories.map((category) => <article key={category.id} className="flex flex-col gap-4 rounded-xl border border-zinc-200 p-4 sm:flex-row sm:items-center"><img src={category.imageUrl ?? category.image} alt="" className="h-20 w-full rounded-xl object-cover sm:size-16" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{category.name}</h2><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${category.isActive ? 'bg-emerald-100 text-emerald-800' : 'bg-zinc-100 text-zinc-500'}`}>{category.isActive ? 'Activa' : 'Archivada'}</span></div><p className="mt-1 text-sm text-zinc-500">{category.description}</p><p className="mt-1 text-xs text-zinc-400">{category._count?.products ?? 0} productos · orden {category.sortOrder ?? 0}</p></div><div className="flex gap-2"><button type="button" onClick={() => edit(category)} className="grid size-10 place-items-center rounded-xl border border-zinc-200 hover:text-violet-700" aria-label="Editar"><Edit3 size={17} /></button>{category.isActive && <button type="button" onClick={() => void archive(category)} className="grid size-10 place-items-center rounded-xl border border-zinc-200 hover:text-red-600" aria-label="Archivar"><Archive size={17} /></button>}</div></article>)}{categories.length === 0 && <p className="py-10 text-center text-zinc-500">Cargando categorías...</p>}</div></Panel>
    <Panel className="xl:sticky xl:top-8"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-extrabold">{editingId ? 'Editar categoría' : 'Nueva categoría'}</h2>{editingId && <button type="button" onClick={reset} className="grid size-9 place-items-center rounded-lg hover:bg-zinc-100"><X size={18} /></button>}</div><form onSubmit={submit} className="mt-5 grid gap-4"><label className="text-sm font-bold">Nombre<input className={`${inputClass} mt-2`} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value, slug: editingId ? form.slug : event.target.value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') })} required /></label><label className="text-sm font-bold">Slug<input className={`${inputClass} mt-2`} value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} required /></label><label className="text-sm font-bold">Descripción<textarea className={`${inputClass} mt-2 min-h-24 py-3`} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} required /></label><div><span className="text-sm font-bold">Imagen</span><div className="mt-2"><CloudinaryImageUploader folder="categories" onUploaded={(url) => setForm((current) => ({ ...current, imageUrl: url }))} /></div>{form.imageUrl && <img src={form.imageUrl} alt="Vista previa de la categoría" className="mt-3 aspect-[16/9] w-full rounded-xl border border-zinc-200 object-cover" />}<label className="mt-3 block text-xs font-bold text-zinc-600">URL de imagen<input className={`${inputClass} mt-2`} type="url" value={form.imageUrl} onChange={(event) => setForm({ ...form, imageUrl: event.target.value })} required /></label></div><label className="text-sm font-bold">Orden<input className={`${inputClass} mt-2`} type="number" min="0" value={form.sortOrder} onChange={(event) => setForm({ ...form, sortOrder: Number(event.target.value) })} /></label><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} className="size-5 accent-violet-700" /> Categoría activa</label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button type="submit" className={primaryButton}>{editingId ? <Save size={17} /> : <Plus size={17} />}{editingId ? 'Guardar cambios' : 'Crear categoría'}</button>{editingId && <button type="button" onClick={reset} className={secondaryButton}>Cancelar</button>}</form></Panel></div>
  </>
}