import { ShieldCheck, UserPlus } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { AdminPageHeader, Panel, inputClass, primaryButton } from '../../components/admin/AdminUi'
import { adminApi } from '../../services/api'
import type { AdminRole, AdminUser } from '../../types'

export function AdminUsersPage() {
  const [users, setUsers] = useState<AdminUser[]>([])
  const [form, setForm] = useState({ name: '', email: '', password: '', role: 'ADMIN' as AdminRole })
  const [message, setMessage] = useState<string | null>(null)
  const load = () => adminApi.get<{ data: { users: AdminUser[] } }>('/admin/users').then(({ data }) => setUsers(data.users)).catch((err) => setMessage(err.message))
  useEffect(() => { void load() }, [])
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await adminApi.mutate('/admin/users', { method: 'POST', body: JSON.stringify(form) }); setForm({ name: '', email: '', password: '', role: 'ADMIN' }); setMessage('Administrador creado.'); load() } catch (err) { setMessage(err instanceof Error ? err.message : 'No se pudo crear.') } }
  const toggle = async (user: AdminUser) => { try { await adminApi.mutate(`/admin/users/${user.id}/status`, { method: 'PATCH', body: JSON.stringify({ isActive: !user.isActive }) }); load() } catch (err) { setMessage(err instanceof Error ? err.message : 'No se pudo actualizar.') } }
  return <><AdminPageHeader eyebrow="SEGURIDAD" title="Administradores" description="Crea accesos individuales y desactiva cuentas que ya no deban entrar." /><div className="grid items-start gap-6 xl:grid-cols-[1fr_390px]"><Panel><div className="grid gap-3">{users.map((user) => <div key={user.id} className="flex flex-col gap-4 rounded-xl border border-zinc-200 p-4 sm:flex-row sm:items-center"><span className="grid size-11 place-items-center rounded-full bg-violet-100 font-bold text-violet-700">{user.name.charAt(0)}</span><div className="min-w-0 flex-1"><p className="font-bold">{user.name}</p><p className="truncate text-sm text-zinc-500">{user.email}</p></div><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-bold">{user.role}</span><button type="button" onClick={() => void toggle(user)} className={`rounded-xl px-3 py-2 text-xs font-bold ${user.isActive ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`}>{user.isActive ? 'Desactivar' : 'Activar'}</button></div>)}</div></Panel><Panel className="xl:sticky xl:top-8"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-violet-100 text-violet-700"><UserPlus size={20} /></span><h2 className="font-display text-xl font-extrabold">Nuevo acceso</h2></div><form onSubmit={submit} className="mt-5 grid gap-4"><label className="text-sm font-bold">Nombre<input className={`${inputClass} mt-2`} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label className="text-sm font-bold">Correo<input type="email" className={`${inputClass} mt-2`} value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><label className="text-sm font-bold">Contraseña temporal<input type="password" minLength={12} className={`${inputClass} mt-2`} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /><span className="mt-1 block text-xs font-normal text-zinc-400">Mínimo 12 caracteres.</span></label><label className="text-sm font-bold">Rol<select className={`${inputClass} mt-2`} value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as AdminRole })}><option value="ADMIN">Administrador</option><option value="SUPERADMIN">Superadministrador</option></select></label><button className={primaryButton}><ShieldCheck size={17} /> Crear administrador</button>{message && <p className="rounded-xl bg-violet-50 p-3 text-sm text-violet-800">{message}</p>}</form></Panel></div></>
}
